### ISSUE TITLE
Incompatible with Xcode 15 (Stored properties cannot be marked unavailable with '@available')

### ISSUE THREAD

**Issue by nattnh751** [gordontucker/FittedSheets#218] opened 2023-10-19 21:25 UTC
This issue represents when upgrading to xcode 15.  

Happens in the file `SheetOptions.swift`
<img width="1142" alt="Screenshot 2023-10-19 at 4 24 17 PM" src="https://github.com/gordontucker/FittedSheets/assets/56076848/0003f09c-ce0e-41a5-a097-40e8243c20e6">

Lines 49-62.

**Comment by AndrewSB** [comment] 2023-10-25 17:34
dupe of #218 #215 #213 #214

update to the latest version of this package: [2.6.1](https://github.com/gordontucker/FittedSheets/releases/tag/2.6.1)

**Closed by AndrewSB** 2023-10-25 17:34 UTC

**Comment by nattnh751** [comment] 2023-10-31 14:58
Sorry for the dupe, just didn't realize it because that version isn't marked on your release page https://github.com/gordontucker/FittedSheets/releases. Thank you for the support!

**Comment by AndrewSB** [comment] 2023-10-31 21:41
no worries! thanks for pointing that out, just marked that tag as our latest release https://github.com/gordontucker/FittedSheets/releases/tag/2.6.1
